branch-defaults:
  default:
    environment: torchci
environment-defaults:
  torchci:
    branch: null
    repository: null
global:
  application_name: pytorch-ci-hud
  default_ec2_keyname: suo
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
