name: Disable Flaky Tests

on:
  schedule:
    # At minute 39 past every 3rd hour Monday through Friday.
    - cron: "39 */3 * * 1-5"
  pull_request:
    paths:
      - ".github/workflows/disable-flaky-tests.yml"
  # Have the ability to trigger this job manually through the API
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-18.04
    steps:
      - name: Fetch and file issues for flaky tests
        run: |
          curl --request POST \
          --url 'https://www.torch-ci.com/api/flaky-tests/disable' \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'