name: sync_pytorch_canary

on:
  schedule:
    # Every hour at the 43rd minute
    - cron: "43 * * * *"
  # Have the ability to trigger this job manually through the API
  workflow_dispatch:

jobs:
  sync-pytorch:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up SSH
        env:
          PYTORCH_CANARY_SSH_PRIVATE_KEY: ${{ secrets.PYTORCH_CANARY_SSH_PRIVATE_KEY }}
        run: |
          set -eu
          mkdir -p ~/.ssh
          echo "$PYTORCH_CANARY_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Clone pytorch/pytorch
        run: |
          git clone --bare git@github.com:pytorch/pytorch.git pytorch
      - name: Mirror push to pytorch/pytorch-canary
        run: |
          set -eu
          export GIT_SSH_COMMAND="ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no"
          cd pytorch

          # This was previously just a git push --mirror, but that ran into issues as pytorch/pytorch
          # has too many branches. The following solution was derived from a StackOverflow:
          # https://stackoverflow.com/questions/54828301/git-error-when-pushing-remote-failed-to-report-status
          git gc
          git push --tags git@github.com:pytorch/pytorch-canary.git
          git branch -a --format "%(refname)" | xargs -i bash -c "git symbolic-ref HEAD {} && git push git@github.com:pytorch/pytorch-canary"
