name: Update disabled tests

on:
  schedule:
    # Every 15 minutes
    - cron: "*/15 * * * *"
  # Have the ability to trigger this job manually through the API
  workflow_dispatch:

jobs:
  update-disabled-tests:
    runs-on: ubuntu-18.04
    steps:
      - name: Generate new disabled test list
        run: |
          # score changes every request, so we strip it out to avoid creating a commit every time we query.
          curl 'https://api.github.com/search/issues?q=is%3Aissue+is%3Aopen+repo:pytorch/pytorch+in%3Atitle+DISABLED&page=1&per_page=100' \
          | sed 's/"score": [0-9\.]*/"score": 0.0/g' > disabled-tests.json
      - name: Sort disabled-tests.json
        shell: python
        run: |
          import json
          with open('disabled-tests.json') as file:
            disabled_tests_json = json.load(file)

          # Sort disabled test issues by URL, e.g., https://api.github.com/repos/pytorch/pytorch/issues/38491
          disabled_tests_json['items'].sort(key=lambda x: x['url'])

          with open('disabled-tests.json', mode='w') as file:
              json.dump(disabled_tests_json, file, sort_keys=True, indent=2)
      - name: Push file to test-infra repository
        uses: dmnemec/copy_file_to_another_repo_action@5f40763ccee2954067adba7fb8326e4df33bcb92
        env:
           API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source_file: 'disabled-tests.json'
          destination_repo: 'pytorch/test-infra'
          destination_folder: 'stats'
          destination_branch: main
          user_email: 'test-infra@pytorch.org'
          user_name: 'Pytorch Test Infra'
          commit_message: 'Updating disabled tests stats'
